### ISSUE TITLE
"Original size" bug 

### ISSUE THREAD

**Issue by shu307** [jurplel/qView#374]
**Environment:**
- OS: 
Windows 10 64bit 
20H2 
19042.685
Display resolution : 3840x2160

- qView version: 4.0

**Information:**
When system Settings "Display"-"Scale and layout" is above 100%, "Original size" gets incorrect size.
So I rolled back to version 3.0.

**Comment by jurplel** [comment]
Can you please demonstrate exactly the behavior you are looking for and how it has changed? Comparison pictures would be helpful.

**Comment by shu307** [comment]
# SAME PNG FILE, SAME  "DISPLAY" WINDOW, DEFAULT SETTINGS.
# version3
- Open file for the first time, a bit blurry.
![version3-firstopen](https://user-images.githubusercontent.com/26036149/102481315-85468800-409c-11eb-94d7-0aa41dc91ffe.png)
- After click "Original Size", very clear.
![version3-original](https://user-images.githubusercontent.com/26036149/102481342-90011d00-409c-11eb-8cd8-ab7998afd2b0.png)
everything is normal.
# version4
- Open file for the first time.
**Note that in the upper left corner, it's a picture, not my desktop. The 1920X1200 picture almost fills my screen**

![version4-firstopen](https://user-images.githubusercontent.com/26036149/102481747-1ddd0800-409d-11eb-81f4-3453ad436eeb.png)
- After click "Original Size".
![version4-original](https://user-images.githubusercontent.com/26036149/102481764-26cdd980-409d-11eb-9bbe-87c35162669c.png)

**Comment by shu307** [comment]
just set the system scaling to 150% or 200%, then open a picture and see what happens

**Comment by jurplel** [comment]
This was actually supposed to be intentional, but clearly I need to add an option.

**Comment by elman22** [comment]
> This was actually supposed to be intentional.

Interesting idea, but I've never seen any image viewer that scales images like qView does.

If I have 4K display with 200 % scaling and I download 4K picture and view it fullscreen, I would expect it to be displayed in perfect 1:1 ratio. Since qView scales images, I assume it would blow picture to 8K and then downscale it to 4K and I would loose picture clarity since it would be presented basically in HD.

So thank you for adding this to 5.0 milestone.

**Comment by jurplel** [comment]
Well the original bug report that led me to change it to this behavior argued that it is idiomatic on Mac. On mac, preview.app actually works this way.

**Comment by elman22** [comment]
Hmm.. Never worked with Mac. Maybe it generates retina image @2...

Anyway, I guess an option would be the best way to go to please everybody.

**Comment by rezad1393** [comment]
I have the same issue on linux.
when I use kde plasma on wayland and use 200% display setting scaling (integer scaling, as fractional scaling has issues with wayland right now), and try to view a 1080p picture on my 1080p screen, the image get stretched two times.
it seems that qview thinks my screen is a 540p screen.

other image viewer dont do this and correctly only use scaling for their UI element.

**Comment by jdpurcell** [comment]
There are two ways this could be expected to work:

1. A 1920-wide image on a 3840-wide display is always shown pixel-for-pixel and takes up half of the display's width.
2. That same image is adjusted for the display's scaling factor, 1.5 (150%) for example as reported by this issue's author, in which case the image takes up 75% of the display's width.

There is no right way to do it, it's probably best to have a setting for it. Different programs handle it differently; image editors/viewers on Windows typically(?) do # 1, and web browsers do # 2. On macOS it usually only makes sense to do # 2 due to the way macOS handles display scaling - it's often rendering to a virtual desktop larger than the native resolution and scaling down; there's no guarantee that one pixel drawn will equal one pixel on the display.

That said, the specific problem @shu307 was having goes further. If you notice, qView was making the 1920-wide image take up 100% of the display which matches neither of the expected behaviors. This is due to the way Qt handled DPI scaling prior to Qt6. [Qt::HighDpiScaleFactorRoundingPolicy](https://doc.qt.io/qt-5/qt.html#HighDpiScaleFactorRoundingPolicy-enum) defaulted to `Round` which results in a 2.0 scale factor when Windows is set to 150% scaling. As of Qt6, the default has been changed to `PassThrough`.

So this is actually kind of fixed in the nightly Win64 builds because those use Qt6 now after @jurplel switched from Azure Pipelines to GitHub Actions. As for the Win32 builds, it could be fixed such as I did in [my commit here](https://github.com/jdpurcell/qView/commit/656b0f70110b25850f549ebde70fde6aaf23d8d7).

**Comment by rezad1393** [comment]
I dont know about macOS, but I think the first way is the correct way.
if you tell the program to show the image (collection of pixels) at the original size, then it should show pixel to pixel. this way use sees the original image. and scaling rounding and other issues are not present.

I think the same way as I would about a movie.
a movie played should play a 1080p movie on a 1080p physical screen pixel to pixel in full screen, regardless of scale. even though mpv in linux right now cant on wayland.
scaling in for vectors not for images.

and web browsers do it so that the web layout don't gets messed up.
an image or video player doesn't have this issue.

**Comment by jdpurcell** [comment]
I implemented an option called "Zoom level is relative to screen pixels" in my repo to make 1 image pixel equal 1 screen pixel @ 100% zoom level. Maybe that or something similar could be integrated into the official qView some day. It was a little tricky to get right and handle the window getting dragged across different displays with varying scaling settings or the scaling setting getting changed on the current display, but I think I got it all working.

**Comment by jurplel** [comment]
> I implemented an option called "Zoom level is relative to screen pixels" in my repo to make 1 image pixel equal 1 screen pixel @ 100% zoom level. Maybe that or something similar could be integrated into the official qView some day. It was a little tricky to get right and handle the window getting dragged across different displays with varying scaling settings or the scaling setting getting changed on the current display, but I think I got it all working.

I would be interested in a PR with this change + your change for the PassThrough tweak above

**Comment by rezad1393** [comment]
> I implemented an option called "Zoom level is relative to screen pixels" in my repo to make 1 image pixel equal 1 screen pixel @ 100% zoom level. Maybe that or something similar could be integrated into the official qView some day. It was a little tricky to get right and handle the window getting dragged across different displays with varying scaling settings or the scaling setting getting changed on the current display, but I think I got it all working.

I always thought that was what "%100 size" or "natural size" was. and at least in xorg it is.
but in wayland it has issues.
my suggestion is to wait for wayland new fractional scaling to work and then implement what you want.
if you do it before that you may need some hacks to make it work.
although wayland scaling with integer scales also has some issues still.

**Comment by the01player** [comment]
This fix would be very much appreciated, it's the only big issue keeping me from using qView at the moment, because I need to see the pixel perfect versions of my photos and not a scaled version. Thank you all for your hard work :)

**Comment by gopgnz** [comment]
> I implemented an option called "Zoom level is relative to screen pixels" in my repo to make 1 image pixel equal 1 screen pixel @ 100% zoom level. Maybe that or something similar could be integrated into the official qView some day. It was a little tricky to get right and handle the window getting dragged across different displays with varying scaling settings or the scaling setting getting changed on the current display, but I think I got it all working.

Please consider releasing this as a new version. I love qView but now that I'm using a 4k screen the images are indeed scaled up beyond their actual resolution. So even viewing the original size is blow up slightly and appears blurrier. I would love to have the option to view pixel 1:1. Sadly I have no experience how to build an installer myself from PR.

**Comment by jdpurcell** [comment]
@gopgnz This repo thankfully has automated builds, the Windows build from the latest run of my PR #699 is [here](https://github.com/jurplel/qView/actions/runs/12342422911/artifacts/2323437246). If you're curious how to find those links in the future, if you go to my PR and scroll near the bottom where it says "All checks have passed" and click "Show all checks". Then click Details for any one of them, and near the top left click Summary. At the bottom of that summary page are the download links for the automated build.

**Comment by gopgnz** [comment]
@jdpurcell Thanks a lot! Especially for the quick reply! I just tested it and it works exactly like I hoped. Now the images are viewed at the exact scale. Thanks a lot!

**Comment by gopgnz** [comment]
I don't know what happened but recently qview stopped viewing images at true scale. Perhaps some Windows update affected it somehow? Now images are again shown scaled up instead of their true size on my 4k screen. I even uninstalled and re-installed it but the issue remains. Does anyone know how it can be fixed again?

**Comment by Kingistador** [comment]
I recently found qview, which is basically all I ever needed from an image viewer.
But I also found that when the scale in Windows is different from 100%, the "original size" of the image does not correspond 1 to 1 to the size of the display's pixel, which is critical for my work and visually it also looks strange when everything is larger on the screenshot opened in qview than in the original.
This is the first time I see such behavior when setting the original size in an image viewer.
It would be really good to have at least the ability to choose the behavior of the scale, although it seems obvious to me that the image in the original size should correspond to real pixels.
I saw that on the Mac there is a slightly different problem, but I think in general the goal is the same - the screenshot in qview should be visually the same size as what the screenshot was taken from, without resizing, interpolation or anti-aliasing.

**Comment by gopgnz** [comment]
> [@gopgnz](https://github.com/gopgnz) This repo thankfully has automated builds, the Windows build from the latest run of my PR [#699](https://github.com/jurplel/qView/pull/699) is [here](https://github.com/jurplel/qView/actions/runs/12342422911/artifacts/2323437246). If you're curious how to find those links in the future, if you go to my PR and scroll near the bottom where it says "All checks have passed" and click "Show all checks". Then click Details for any one of them, and near the top left click Summary. At the bottom of that summary page are the download links for the automated build.

Sadly the issue persist to this day. I tried the newest version and even the nightly but the images are still being scaled on my 4k screen. I am now on Windows 11 and was hoping it might magically work but sadly qView still doesn't show 1-to-1 pixels. Hence images are always being shown bigger than they actually are when viewed in "Original Size". I love this app so much but I require to see the actual image size for my work. Really hope you could fix this issue. Many thanks in advance.

**Comment by WildByDesign** [comment]
Yeah it seems a little crazy that this mainline project hasn’t brought in the code for this that @jdpurcell fixed years ago in that forks’ builds.

**Comment by gopgnz** [comment]
> Yeah it seems a little crazy that this mainline project hasn’t brought in the code for this that [@jdpurcell](https://github.com/jdpurcell) fixed years ago in that forks’ builds.

Sadly the link that was provided in his post above doesn't work anymore. Not sure if there's another fork build that still works to this day regarding this issue.

**Comment by elman22** [comment]
I like qView but couldn't commit to it because of several issues I was having:
- Couldn't view images 1:1 on 4K display
- Couldn't filter out ARW images
- Window auto-resize feature would quite often place window partially off-screen so I always had to move it.

Fortunately I just found fork https://github.com/jdpurcell/qView and it fixes all of them! I switched to AppImage and no issues so far. Thank you @jdpurcell .

**Comment by gopgnz** [comment]
> I like qView but couldn't commit to it because of several issues I was having:
> 
>     * Couldn't view images 1:1 on 4K display
> 
>     * Couldn't filter out ARW images
> 
>     * Window auto-resize feature would quite often place window partially off-screen so I always had to move it.
> 
> 
> Fortunately I just found fork https://github.com/jdpurcell/qView and it fixes all of them! I switched to AppImage and no issues so far. Thank you [@jdpurcell](https://github.com/jdpurcell) .

Thank you so much for your comment! I realized only now that I was mistaken about the fork build. For some reason I thought the fork was once done by the original author of qView and couldn't find a release for it on this main github. Only now I realized that @jdpurcell is not @jurplel ... thanks to your comment I now downloaded the fork and like you said it fixed all my problems. Many thanks @jdpurcell for your contribution on top of the work that jurplel did. I am beyond happy with the software now. I set images to always zoom to fit the window but that images don't automatically zoom beyond 100% when you open them. That way huge images are shown at smaller scale to fit the window but smaller images are shown at their original size (without getting scaled up). Now it's absolutely a treat to use on my 4K screen.

**Comment by BriellaBugs** [comment]
Will this ever be fixed?

**Comment by jurplel** [comment]
Yes it will be fixed at some point.
