### ISSUE TITLE
Slow image loading and switching

### ISSUE THREAD

**Issue by Ichisich** [jurplel/qView#476]
- OS: [Windows 10 Build 19044.1415]
- qView version: [5.0 64bit]

Image switching and loading speed heavily correlates with image quantity in the given folder.
It gets noticeable above 200 images and slows down to a crawl the higher the number.

Image format, disk speed (HDD, SSD), preloading setting and sorting/position has meagre to no impact.

qView 4.0 already had this problem but not as distinct as 5.0.

**Comment by LolicoreExpress** [comment]
Yes, seconded. I've got a 10k+ folder and it's basically impossible to even get a an image to load in qView 😂

**Comment by jurplel** [comment]
Ah, you see I have not been testing with folders with that many images. Do you think the loading time increases linearly or at a higher order of magnitude?

**Comment by Ichisich** [comment]
Seems to be a linear increase.

**Comment by LolicoreExpress** [comment]
Okay I've got more info. This is weird. It seems that this has more to do with if the files in the folder are "discovered" or not. You know how it takes some time for details like creation date and file type to appear ? 
Well it seems (still not 100% sure but it seems so) that the time it takes for the folder to be entirely discovered is the time it will take before an image can be opened.

I'm currently doing some more testing with varying folder size.

**Comment by Ichisich** [comment]
I tested it with a 100/200/400/2000/4000/6000/8000 folder mainly filled with 1920x1080 .jpg files, on average250-400 KB in size.
The increase is pretty predictable, thus most likely nearly linear.

**Comment by jurplel** [comment]
Ok, so maybe the change to make is if the path is the same as the previous folder, to skip repopulating the list of items in the current folder

**Comment by LolicoreExpress** [comment]
Load times seem to increase quite a bit more when getting to 10k+ files.

5k folder: 3,5s to open, 6s to switch to next image
7k folder: 5s to open, 10s to switch to next image
14k folder: 21s to open, 44s to switch to next image

**Comment by Ichisich** [comment]
Affirmative.

To make approaches:
02k folder 1,4s to open an image.
04k folder 2,6s to open an image. 
08k folder 5,3s to open an image.
16k folder 21,5s to open an image.

Seems there is a threshold

**Comment by calico-cat968** [comment]
Possibly related to #442 

@Ichisich @LolicoreExpress
Have you tried qView 3.0? I have a few folders with 200-300 images and they all load almost instantly with 3.0. It's about the same with 4.0 but noticeably slower with 5.0.

**Comment by vassudanagunta** [comment]
> Ok, so maybe the change to make is if the path is the same as the previous folder, to skip repopulating the list of items in the current folder

Can you load the first image and the folder list in separate threads?

**Comment by Ichisich** [comment]
@calico-cat968 

Yes, qView 3 opens images instantly, regardless of image quantity. 
Only image switching gets somewhat slower, but even with 16k images, switching keeps below one second.

qView 4 acts like 5, just less noticeable.

**Comment by jkananen** [comment]
I am also experiencing performance degrade in the version 5.0, with only some tens of PNGs.

First load is fast, but hitting left / right to move to previous / next image takes more than 2 seconds each time, and it's hard to move several images, because the program is rather unresponsive.

macOS Big Sur 11.6

Ps. Can I download the latest 4.x .dmg somewhere? Thanks.

**Comment by jurplel** [comment]
Yes, you can download previous versions here: https://github.com/jurplel/qView/releases

**Comment by jkananen** [comment]
> Sorry about this.

No reason to say sorry, we all appreciate your efforts.

**Comment by LolicoreExpress** [comment]
> Possibly related to #442
> 
> @Ichisich @LolicoreExpress Have you tried qView 3.0? I have a few folders with 200-300 images and they all load almost instantly with 3.0. It's about the same with 4.0 but noticeably slower with 5.0.

Yup, I've reverted back to 4.0 for the time being.

**Comment by jurplel** [comment]
Culprit for the slowdown is:
```cpp
    QFileInfoList fileInfoList = currentFileDetails.fileInfo.dir().entryInfoList(qvApp->getFilterList(), QDir::Files);

    QMimeDatabase mimeDb;
    QList<QByteArray> supportedMimeTypes = QImageReader::supportedMimeTypes();
    // Qt 5.15 seems to have added pdf support for QImageReader but it is super broken in qView at the moment
    supportedMimeTypes.removeAll("application/pdf");

    const QFileInfoList currentFolder = currentFileDetails.fileInfo.dir().entryInfoList();
    for (const QFileInfo &fileInfo : currentFolder)
    {
        QMimeType mimeType = mimeDb.mimeTypeForFile(fileInfo);
        if (supportedMimeTypes.contains(mimeType.name().toUtf8()))
        {
            if (!fileInfoList.contains(fileInfo)) {
                fileInfoList.append(fileInfo);
            }
        }
    }
```

**Comment by jurplel** [comment]
Open with menu population is responsible too.

**Comment by jurplel** [comment]
Updating open with items with
```
action->setIcon(openWithItem.icon);
```
is somehow very slow. It takes 25ms per call, and is called probably around thirty times.

**Comment by jurplel** [comment]
Running `populateOpenWithMenu` in another thread works, but I get 
```
QObject::startTimer: Timers cannot be started from another thread
```
in the console, as I am using QWidget in another thread, which isn't allowed/doesn't work properly. Open to suggestions on how to speed up `QAction::setIcon`.

**Comment by AlttiRi** [comment]
Well, qView 5.0 is not just slow, it's legendary slow.
An image in a directory with 30k of files was not opened even in 4 minutes (then I just killed the process).

That the program does? 

Technically there is only one thing that is depends on the count of file in a directory — parsing to create a list with the required meta information of files for sorting and navigation purpose. 

qView 4.0 opens it in 3.6 second it. Opening the next image also takes the same time. It looks that qView 4.0 handles the directory each time, while it requires to do only once.

---

Technically and practically qView can be **much faster**.

I did the demo program for that issue https://github.com/easymodo/qimgv/issues/290, but I think it would interested also for you. 
Here is it: https://github.com/AlttiRi/demo-image-viewer

It shows the image in 150 ms from the program run (in the same 30k files directory).
Opening of an image is not depend of the count of the files in the firectory.

Also it parses that 30k directory just in 350 ms in a separate thread.

Take a looks at the [readme](https://github.com/AlttiRi/demo-image-viewer#readme).

---

BTW, you use https://github.com/jurplel/qView/blob/eee6b693e3694876950bada0d47756803b2aed14/src/qvimagecore.cpp#L291-L299
for sorting. 

Check my comment about it in the readme. It's **VERY SLOW** thing. In fact it should work up to 600 times faster, but it looks QT does not cache that values, while it should do.

**Comment by jurplel** [comment]
Yes, certainly there is a big problem. I also found that annoying behavior with the open with menu icon that is slowing things down significantly (recent menu icon probably doesn't help in hindsight either).

I was trying to get the update done before my spring semester started (which I did), but unfortunately I don't have time to give qView the attention it needs at the moment :(

Sidenote: I never tested qView with a folder with over 100 images because i have never had that use case. That is a big design oversight on my part, of course.

**Comment by vassudanagunta** [comment]
You might want to consider pulling the release, or at least putting up a dialog when it starts up, because the bad first impression it's going to give people will undermine its reputation. The nightly-2021.05-19.1 build is much better as a latest release. (i.e. the slow image loading is really bad and I'm on an M1 mac).

**Comment by jurplel** [comment]
> You might want to consider pulling the release, or at least putting up a dialog when it starts up, because the bad first impression it's going to give people will undermine its reputation. The nightly-2021.05-19.1 build is much better as a latest release. (i.e. the slow image loading is really bad and I'm on an M1 mac).

I'll do something—I'll try to see if I can mitigate the issue at all first

Would you say the latest build is still worse than 4.0 when in very big folders? I think it should be the same as 4.0 except there is an extra delay when loading an image due to the icon issue.

**Comment by vassudanagunta** [comment]
ok, I did some tests, on folders with about 120 images, 2.5-3.5MB each. I opened the first image and then held down the spacebar to advance through them.

On folders on my **local SSD**, 5.0 opened the images about twice as fast (my perception, not a precise measurement) as 4.0. This was true for the smaller files as well as the larger. nightly-2021.05-19.1 was the same as 4.0.

But on folders on an **SMB network share** hosted by an old Mac Mini with a **spinning disk** running macOS 10.13, it was an entirely different picture.  4.0 opens the images about the same speed as the local SSD, nightly-2021.05-19.1 about half as fast or less, but 5.0 took about 5 seconds (i used a stopwatch) for each (so at least 10 times slower if not much more). If i held down the space bar I'd see the beach ball. Sometimes 5.0 would get unresponsive.

So my gut says the SSD and its locality is hiding the underlying issue... the disk access is so fast you can't perceive whatever 5.0 is doing inefficiently.

**Comment by jurplel** [comment]
I am curious how the changes here affect things: https://dev.azure.com/jurplel/qView/_build/results?buildId=1091&view=artifacts&pathAsName=false&type=publishedArtifacts

they should have made the folder dependence the same as 4.0

**Comment by vassudanagunta** [comment]
I open the first image in the SMB network share and then held down the space bar for 10 seconds to see how many images each version would get through in that time. I ran the test a few times for each version, always skipping the first run so that i was consistently testing against a warm disk/network cache:

version | number of images in 10 secs
 --- | ---
4.0 | 31-36
qView-nightly.2021-05-19.1 | 10-14
5.0 | 2 images at the 10 sec mark with beach ball spinning, then delayed (long after space bar released) advance to the 3rd and 4th image at 17-25 sec mark.
qView-nightly-2022-01-17.2 | 16-23

**Comment by vassudanagunta** [comment]
Also, the `About qView` popup for `qView-nightly-2022-01-17.2` shows "qView 5.0" instead of what it is, unlike `qView-nightly.2021-05-19.1` which says "qView-nightly.2021-05-19.1".

**Comment by jurplel** [comment]
> Also, the `About qView` popup for `qView-nightly-2022-01-17.2` shows "qView 5.0" instead of what it is, unlike `qView-nightly.2021-05-19.1` which says "qView-nightly.2021-05-19.1".
> 
> 

Thanks, I think I broke the pipeline a while ago.

Performance difference could be because of the aforementioned icon issue. I'll let you know when I address it and we can test again. Thank you for your time, I really appreciate it.

Also, since 5.0 release, I fixed a bug specifically causing holding the arrow to not load images properly, so that might not be a fair comparison for 5.0.

Thanks again!

**Comment by AlttiRi** [comment]
Also I can say that preloading/caching of the adjacent images is not working, while I see in the repo [a code for that](https://github.com/jurplel/qView/blob/eee6b693e3694876950bada0d47756803b2aed14/src/qvimagecore.cpp#L340-L416) and it is enabled by default in the settings. 
(I tested it with qView 4.0)

I added [this thing](https://github.com/AlttiRi/demo-image-viewer/blob/908abbe6542a6dea1d4cc329c317059636779c2c/core.h#L57-L96) in my demo program, so I can say if you have a preloaded images (`QPixmap`) the switching is fast. It takes 25 ms for a 45 MP photo, while the loading of that big image takes 350-450 ms.

---

How to test it: open one image in a folder with big images, wait 500 ms for the preloading is completed, then go to the next (or previous) image — you will see the delay, it means that caching does not work.

UPD: 
It can be easily detected by the memory consuming. It shows that qView does not store the preloaded `QPixmap`.
Memory consuming of my demo program is almost the same as qimgv's one.
It preloads one image before (if exists) the opened image and one after (if exists).

**Comment by aki009** [comment]
The latest source has this issue addressed for the most part. I made a few additional changes that may or may not be worthy of consideration for addition to the project. YMMW. IWOMM (It Works On My Machine). It's still not as fast as I'd like. There is no reason 36 billion screaming opportunities for computing per second can't load a measly 4MB image file faster than the second or so it seems to take.

[helpwithslowload.diff.txt](https://github.com/jurplel/qView/files/8806621/helpwithslowload.diff.txt)

**Comment by aki009** [comment]
> UPD2: Wait, there is [a cache limitation](https://github.com/jurplel/qView/blob/eee6b693e3694876950bada0d47756803b2aed14/src/qvimagecore.cpp#L531-L542), 50 KB and 200 KB. Caching is only for tiny files? Such files even without caching will be opened fast.

The argument is in kilobytes. So it's 50 megs and 200 megs.

**Comment by aki009** [comment]
While waiting for 5.1, I made an interim 5.0 that has faster folder handling. I only compiled it for Macs. No guarantees of any type for how well this version will work for you. "It works on my machine."

[https://github.com/aki009/qView](url)

**Comment by AlttiRi** [comment]
> The argument is in kilobytes. So it's 50 megs and 200 megs.

Anyway, it just does not work. Just try to navigate through 30+ MB images folder.
The caching/preloading should be done manually like it is in [my example](https://github.com/AlttiRi/demo-image-viewer/blob/3f5033b6fddf8580ef2d0349762c617d3bc61a28/core.h#L59-L98). BTW, [qimgv](https://github.com/easymodo/qimgv) works the same way.

**Comment by herrenP** [comment]
Not sure if this is already apparent to the devs.

It seems to me the amount of time is affected but not only the amount of image files but also other files. I have a folder with a lot of mp4s and for each mp4 there's a webp or a jpg file as well as some regular text files. If I try to open the images in this folder it takes much longer than if I would open the same image files that has been copied to another location where these "other files" do not exist. It's like QView tries to analyze the other files as well.

Thanks for a cool software!

**Comment by jdpurcell** [comment]
If anyone would like to try my pull request (#517), the nightly builds are available here:
https://dev.azure.com/jurplel/qView/_build/results?buildId=1135&view=artifacts&type=publishedArtifacts

It still refreshes the directory listing every time when switching images (I may do something about that later), but I managed to speed it up significantly.

**Windows notes**
The zip contains two .exe files, you can run the smaller of the two named qView-nightly-* (the other one is the installer).
An extra setting may help performance in some cases (especially with network shares). It's not in the UI, but can be added to the registry via command prompt (make sure qView isn't running first):
`reg add HKEY_CURRENT_USER\SOFTWARE\qView\qView\options /v allowmimecontentdetection /t REG_SZ /d false`

**Mac notes**
The download labeled "macos" is the normal one for macOS 10.14+, the "macosx" nightly is the legacy version for 10.12+. 
Two extra settings may help performance in some cases (especially with network shares). They're not in the UI, but can be added to the preferences via terminal (make sure qView isn't running first):
`defaults write com.qview.qView allowmimecontentdetection -bool FALSE`
`defaults write com.qview.qView showhiddenfiles -bool TRUE`

**Linux notes**
¯\\\_(ツ)\_/¯ Not tested

**Comment by LolicoreExpress** [comment]
> If anyone would like to try my pull request (#517), the nightly builds are available here: https://dev.azure.com/jurplel/qView/_build/results?buildId=1135&view=artifacts&type=publishedArtifacts

Just tried it on Windows and it works wonderfully. Images loads in like 1.5 seconds in a 40k images folder. Thanks a lot !

**Comment by LolicoreExpress** [comment]
> > If anyone would like to try my pull request (#517), the nightly builds are available here: https://dev.azure.com/jurplel/qView/_build/results?buildId=1135&view=artifacts&type=publishedArtifacts
> 
> Just tried it on Windows and it works wonderfully. Images load in like 1.5 seconds in a 40k images folder. It's night and day haha, thanks a lot.

Little update regarding this.
After booting up my computer, the first time I open an image from a (big) folder will be slow. And then, subsequent image opening will be quick, as they should with this fix. But opening another image from another folder will be slow, and again, subsequent launches will be quick. 
So essentially, the first image opening from any (big) folder will be slow, and subsequent openings in the same folder will be quick.
Anybody else experience the same thing ?

**Comment by jdpurcell** [comment]
> After booting up my computer, the first time I open an image from a (big) folder will be slow. And then, subsequent image opening will be quick, as they should with this fix.

Is this with your original settings or did you try the registry command to change the new `allowmimecontentdetection` setting? The setting is in the UI in the [latest nightly](https://dev.azure.com/jurplel/qView/_build/results?buildId=1144&view=artifacts&type=publishedArtifacts) now by the way (and defaults to off if you haven't already run a recent nightly build), so no need to mess with the registry any more; just make sure "Allow MIME content detection" in the Miscellaneous tab is NOT checked.

Also what is your "Sort files by" setting? This can have an impact on performance as well.

**Comment by LolicoreExpress** [comment]
> Is this with your original settings or did you try the registry command to change the new `allowmimecontentdetection` setting? The setting is in the UI in the [latest nightly](https://dev.azure.com/jurplel/qView/_build/results?buildId=1144&view=artifacts&type=publishedArtifacts) now by the way (and defaults to off if you haven't already run a recent nightly build), so no need to mess with the registry any more; just make sure "Allow MIME content detection" in the Miscellaneous tab is NOT checked.

This is with my original settings, I did not try the registry command, so if I understand correctly this setting is ON right now for me ? Well then I will try the new nightly build and try with this setting OFF and see if that helps.

> Also what is your "Sort files by" setting? This can have an impact on performance as well.

Hmm, most folders I tried were sorted by Name, but a couple were sorted by Type or Date. Though I didn't notice any difference. And that initial long loading time seemed to behave the same across folders. (again, all pretty big folder, no small ones).

**Comment by jdpurcell** [comment]
> This is with my original settings, I did not try the registry command, so if I understand correctly this setting is ON right now for me ? Well then I will try the new nightly build and try with this setting OFF and see if that helps.

That is correct. The 2022-10-28 nightly defaulted it to on to preserve the existing behavior of qView 5.0, but given how much it can slow things down, I made a code change in my PR to turn it off by default. If you already ran the 2022-10-28 nightly, it saved a default value, so you would need to uncheck the setting when running the 2022-10-30 nightly.

**Comment by jurplel** [comment]
I will mark this broad issue as closed in light of the latest PRs.
